"""Snake report: docs/snake-report/template.html -> docs/snake-report/index.html, plus the markdown twin
docs/snake-report.md (+ docs/snake-report/probe.svg) via build_md.py. Both render the same data.

  uv run python docs/snake-report/build.py

Data: results/snake/probe-*.json and the per-move game logs in results/snake/games/ (git-ignored, regenerated by
09_snake_benchmark.py). The aggregates the report needs are written to results/snake/report-data.json, which is
committed, so a fresh clone can rebuild the report without the game logs.
"""
import json
import sys
from collections import Counter
from pathlib import Path

R = Path("results/snake")
HERE = Path(__file__).parent
DATA = R / "report-data.json"
MODELS = [("decider", "Decider 2B", "var(--accent)"), ("decider-4b-v2", "Decider 4B", "var(--d4)"),
          ("kev-4b", "Kev 4B", "var(--code)"), ("clm-latest", "CLM 8B", "var(--clm)"),
          ("gliner-decide", "GLiNER 340M", "var(--gl)"), ("gliner-decide-1b", "GLiNER 1B", "color-mix(in srgb, var(--gl) 55%, var(--muted))"),
          ("laya", "Laya", "var(--muted)")]
REQS = [("grid", "Raw board"), ("relative", "Relative, in words"), ("facts", "Facts in the options (sorrycc)"),
        ("judged+state", "Judged options + heading in state"), ("judged", "Judged options, verdicts only"),
        ("judged-plain", "Judged, eating worded as 'closer'")]
NAMES = {"grid": "Raw board", "relative": "Relative, in words", "facts": "Facts in the options", "judged": "Judged options",
         "judged-plain": "Judged, plain wording", "composed": "Composed questions", "random": "random safe move",
         "greedy": "greedy", "greedy-safe": "greedy + dead-end check"}
LABEL = {m: l for m, l, _ in MODELS}
KEYWORD = {"keyword": "Keyword scorer, top score", "keyword-sample-0.5": "Keyword scorer, sampled T=0.5",
           "keyword-sample": "Keyword scorer, sampled T=1"}          # snake.engine.KeywordEngine: no model


def ended_by(cause):
    return ("starved" if cause.startswith("starved") else "step cap (500)" if cause == "max steps"
            else "died" if cause.startswith(("hit", "rev")) else cause)


def aggregate(d):
    """One benchmark file -> the numbers the report shows for its row."""
    s = d["summary"]
    ms = [x["latency_ms"] for g in d["games"] for x in g["decisions"] if x["source"] == "model"]
    row = {k: s[k] for k in ("engine", "name", "games", "score_mean", "score_max", "steps_mean", "latency_p50_ms")}
    row["latency_mean_ms"] = sum(ms) / len(ms) if ms else None
    row["died"] = sum(g["cause"].startswith(("hit", "rev")) for g in d["games"])
    row["ended"] = dict(Counter(ended_by(g["cause"]) for g in d["games"]))
    if s["name"] == "composed":                          # who picked each move: the model, or ximing's code gate
        c = Counter()
        for g in d["games"]:
            for x in g["decisions"]:
                h = x["how"] or ""
                c["code1" if x["source"] == "code" else "surv" if h.startswith("survival")
                  else "low" if h.startswith("low confidence") else "model"] += 1
        n = sum(c.values()) or 1
        row["split"] = {k: c[k] / n for k in ("model", "low", "surv", "code1")}
    return row


def load():
    probe = {m: json.load(open(R / f"probe-{m}.json"))["results"] for m, _, _ in MODELS if (R / f"probe-{m}.json").exists()}
    files = sorted((R / "games").glob("*.json"))
    if files:
        games = [json.load(open(p)) for p in files]
        main = [d for d in games if d["summary"]["engine"] in LABEL or d["summary"]["engine"] == "code"]
        data = {"config": main[0]["config"], "rows": [aggregate(d) for d in main],
                "keyword": [aggregate(d) for d in games if d["summary"]["engine"] in KEYWORD]}
        for c in ("only", "engine"):
            data["config"].pop(c, None)
        DATA.write_text(json.dumps(data, indent=1))
    elif DATA.exists():
        data = json.loads(DATA.read_text())
    else:
        sys.exit("no game logs in results/snake/games/ and no results/snake/report-data.json: run 09_snake_benchmark.py")
    order = {m: i for i, (m, _, _) in enumerate(MODELS)} | {"code": 99}
    fo = {k: i for i, k in enumerate(NAMES)}
    data["rows"].sort(key=lambda r: (order.get(r["engine"], 50), fo.get(r["name"], 99)))
    data["probe"] = probe
    data["keyword_probe"] = {k: json.load(open(R / f"probe-{k}.json"))["results"] for k in KEYWORD
                             if (R / f"probe-{k}.json").exists()}
    return data


def keyword_rows(data):
    """-> (judged rows for the keyword table, one line on the other requests), shared by the HTML and the markdown."""
    kp = data["keyword_probe"]
    order = {k: i for i, k in enumerate(KEYWORD)}
    rows = []
    for r in sorted((r for r in data["keyword"] if r["name"] in ("judged", "judged-plain")),
                    key=lambda r: (order[r["engine"]], r["name"] != "judged")):
        pr = kp.get(r["engine"], {}).get(r["name"], {}).get("hard", {}).get("good")
        rows.append({"who": f"{KEYWORD[r['engine']]} · {NAMES[r['name']]}", "food": f"{r['score_mean']:.1f}",
                     "best": r["score_max"], "died": f"{r['died']} of {r['games']}",
                     "probe": f"{pr:.0%}" if pr is not None else "–", "win": r["engine"] == "keyword"})
    ref = [r for r in data["rows"] if (r["engine"], r["name"]) in (("decider", "judged"), ("code", "greedy-safe"))]
    for r in ref:
        pr = data["probe"].get(r["engine"], {}).get(r["name"], {}).get("hard", {}).get("good")
        rows.append({"who": who(r) + (" (best model)" if r["engine"] == "decider" else ""), "food": f"{r['score_mean']:.1f}",
                     "best": r["score_max"], "died": f"{r['died']} of {r['games']}",
                     "probe": f"{pr:.0%}" if pr is not None else "–", "ref": True})
    other = {r["name"]: r for r in data["keyword"] if r["engine"] == "keyword"}
    line = ", ".join(f"{NAMES[n].lower()} {other[n]['score_mean']:.1f} ({ended_text(other[n])})"
                     for n in ("facts", "relative", "grid") if n in other)
    return rows, line


def best_rows(data):
    """Each model's best request where the model picks every move (composed is excluded: code steps in)."""
    best = {}
    for r in data["rows"]:
        if r["engine"] == "code" or r["name"] == "composed":
            continue
        if r["engine"] not in best or r["score_mean"] > best[r["engine"]]["score_mean"]:
            best[r["engine"]] = r
    return sorted(best.values(), key=lambda r: -r["score_mean"])


def who(r):
    return f"{LABEL.get(r['engine'], r['engine'])} · {NAMES[r['name']]}" if r["engine"] != "code" else f"code only: {NAMES[r['name']]}"


def ended_text(r):
    return ", ".join(f"{k} {v}" for k, v in sorted(r["ended"].items(), key=lambda x: -x[1]))


def html(data):
    probe = data["probe"]
    present = [(m, l, c) for m, l, c in MODELS if m in probe]
    bars, prows = [], []
    for key, label in REQS:
        b = [f'<div class="bar" style="--c:{c}"><div class="track"><div class="fill" style="width:{probe[m][key]["hard"]["good"] * 100:.0f}%"></div>'
             f'<div class="chance"></div></div><div class="val">{probe[m][key]["hard"]["good"] * 100:.0f}%</div></div>'
             for m, _, c in present if key in probe[m]]
        bars.append(f'<div class="grp"><div class="name">{label}</div><div class="bars">{"".join(b)}</div></div>')
        cells = "".join(f'<td class="num">{probe[m][key]["all"]["good"]:.2f} / {probe[m][key]["hard"]["good"]:.2f}</td>'
                        if key in probe[m] else "<td class='num'>–</td>" for m, _, _ in present)
        lat = probe.get("decider", {}).get(key, {}).get("all", {}).get("p50_ms")
        prows.append(f'<tr class="{"win" if key.startswith("judged") and key != "judged+state" else ""}"><td>{label}</td>{cells}'
                     f'<td class="num">{f"{lat:.0f} ms" if lat else "–"}</td></tr>')

    grows = []
    for r in data["rows"]:
        cls = "base" if r["engine"] == "code" else "win" if r["name"] in ("judged", "judged-plain") and r["score_mean"] >= 29 else ""
        lat = f"{r['latency_p50_ms']:.0f} / {r['latency_mean_ms']:.0f} ms" if r["latency_mean_ms"] is not None else "–"
        grows.append(f'<tr class="{cls}"><td>{who(r)}</td><td class="num">{r["score_mean"]:.1f}</td><td class="num">{r["score_max"]}</td>'
                     f'<td class="num">{r["steps_mean"]:.0f}</td><td>{ended_text(r)}</td><td class="num">{lat}</td></tr>')

    crows = [f'<tr><td>{LABEL.get(r["engine"], r["engine"])}</td><td class="num">{r["score_mean"]:.1f}</td>'
             + "".join(f'<td class="num">{r["split"][k]:.0%}</td>' for k in ("model", "low", "surv", "code1")) + "</tr>"
             for r in sorted((r for r in data["rows"] if "split" in r), key=lambda r: -r["score_mean"])]

    brows = []
    for r in best_rows(data):
        pr = probe.get(r["engine"], {}).get(r["name"], {}).get("hard", {}).get("good")
        brows.append(f'<tr class="{"win" if r["score_mean"] >= 29 else ""}"><td>{LABEL[r["engine"]]}</td><td>{NAMES[r["name"]]}</td>'
                     f'<td class="num">{r["score_mean"]:.1f}</td><td class="num">{r["score_max"]}</td><td class="num">{r["died"]} of {r["games"]}</td>'
                     f'<td class="num">{r["latency_mean_ms"]:.0f} ms</td><td class="num">{f"{pr:.0%}" if pr is not None else "–"}</td></tr>')
    code = next((r for r in data["rows"] if r["engine"] == "code" and r["name"] == "greedy-safe"), None)
    if code:
        brows.append(f'<tr class="base"><td>code only</td><td>greedy + dead-end check</td><td class="num">{code["score_mean"]:.1f}</td>'
                     f'<td class="num">{code["score_max"]}</td><td class="num">{code["died"]} of {code["games"]}</td>'
                     '<td class="num">–</td><td class="num">–</td></tr>')

    kw, kw_other = keyword_rows(data)
    krows = [f'<tr class="{"win" if r.get("win") else "base" if r.get("ref") else ""}"><td>{r["who"]}</td>'
             f'<td class="num">{r["food"]}</td><td class="num">{r["best"]}</td><td class="num">{r["died"]}</td>'
             f'<td class="num">{r["probe"]}</td></tr>' for r in kw]

    cfg = data["config"]
    jd = next((r["score_mean"] for r in data["rows"] if r["engine"] == "decider" and r["name"] == "judged"), None)
    return ((HERE / "template.html").read_text()
            .replace("BEST_ROWS", "\n".join(brows)).replace("COMPOSED_ROWS", "\n".join(crows))
            .replace("PROBE_LEGEND", "".join(f'<span style="--c: {c}">{l}</span>' for m, l, c in present))
            .replace("PROBE_HEAD", "".join(f'<th class="num">{l}</th>' for m, l, c in present))
            .replace("PROBE_BARS", "\n".join(bars)).replace("PROBE_ROWS", "\n".join(prows))
            .replace("GAMES_ROWS", "\n".join(grows))
            .replace("KEYWORD_ROWS", "\n".join(krows)).replace("KEYWORD_OTHER", kw_other)
            .replace("GAMES_JUDGED_DECIDER", f"{jd:.0f}" if jd else "–")
            .replace("GAMES_INTRO", games_intro(cfg))
            .replace("GAMES_NOTE", GAMES_NOTE))


def games_intro(cfg):
    return (f"Same {cfg['seeds']} seeds for every row, {cfg['size']}×{cfg['size']} board. A game ends on death, "
            f"after {cfg['size'] ** 2} steps without food (starved), or at {cfg['max_steps']} steps. "
            "Raw board and relative phrasing let the model pick fatal moves; the other requests only offer safe ones.")


GAMES_NOTE = ("Most judged, composed and greedy + dead-end games reach the 500-step cap, so their food counts are capped "
              "too. The code baselines use the same facts the judged options are written from, so the judged request doesn't "
              "beat code at Snake. It matches code while the move stays a model decision, one you can steer with the "
              "strategy text.")


if __name__ == "__main__":
    data = load()
    (HERE / "index.html").write_text(html(data))
    print("wrote", HERE / "index.html")
    sys.path.insert(0, str(HERE))
    import build_md
    build_md.main(data)
